@echo off
REM - programa para preparar a execu‡„o/grava‡„o de tutorial
REM - (apaga *.DB*, *.NTX, *.SYS e consultas gravadas)
echo 
echo                       A T E N € Ž O !
echo Os arquivos de dados do sistema "ADMINISTRADORA - PLANO" ser„o
echo eliminados para execu‡„o da macro. Se desejar cancelar esta opera‡„o
echo pressione CTRL-C AGORA!
PAUSE >NUL
if exist GRUPOS.DB* DEL GRUPOS.DB*
if exist GRU*.NTX DEL GRU*.NTX
if exist DB*.GRU DEL DB*.GRU
if exist ECOB.DB* DEL ECOB.DB*
if exist ECO*.NTX DEL ECO*.NTX
if exist DB*.ECO DEL DB*.ECO
if exist INSCRITS.DB* DEL INSCRITS.DB*
if exist INS*.NTX DEL INS*.NTX
if exist DB*.INS DEL DB*.INS
if exist TAXAS.DB* DEL TAXAS.DB*
if exist TAX*.NTX DEL TAX*.NTX
if exist DB*.TAX DEL DB*.TAX
if exist CANCELS.DB* DEL CANCELS.DB*
if exist CAN*.NTX DEL CAN*.NTX
if exist DB*.CAN DEL DB*.CAN
if exist PRCESSOS.DB* DEL PRCESSOS.DB*
if exist PRC*.NTX DEL PRC*.NTX
if exist DB*.PRC DEL DB*.PRC
if exist EMCARNE.DB* DEL EMCARNE.DB*
if exist EMC*.NTX DEL EMC*.NTX
if exist DB*.EMC DEL DB*.EMC
if exist TCARNES.DB* DEL TCARNES.DB*
if exist TCA*.NTX DEL TCA*.NTX
if exist DB*.TCA DEL DB*.TCA
if exist CSTSEG.DB* DEL CSTSEG.DB*
if exist CST*.NTX DEL CST*.NTX
if exist DB*.CST DEL DB*.CST
if exist BOLETOS.DB* DEL BOLETOS.DB*
if exist BOL*.NTX DEL BOL*.NTX
if exist DB*.BOL DEL DB*.BOL
if exist LBXBOLET.DB* DEL LBXBOLET.DB*
if exist LBX*.NTX DEL LBX*.NTX
if exist DB*.LBX DEL DB*.LBX
if exist BXBOLET.DB* DEL BXBOLET.DB*
if exist BXB*.NTX DEL BXB*.NTX
if exist DB*.BXB DEL DB*.BXB
if exist TXPROC.DB* DEL TXPROC.DB*
if exist TXP*.NTX DEL TXP*.NTX
if exist DB*.TXP DEL DB*.TXP
if exist TX2VIA.DB* DEL TX2VIA.DB*
if exist TX2*.NTX DEL TX2*.NTX
if exist DB*.TX2 DEL DB*.TX2
if exist CLASSES.DB* DEL CLASSES.DB*
if exist CLA*.NTX DEL CLA*.NTX
if exist DB*.CLA DEL DB*.CLA
if exist CLPRODS.DB* DEL CLPRODS.DB*
if exist CLP*.NTX DEL CLP*.NTX
if exist DB*.CLP DEL DB*.CLP
if exist ARQGRUP.DB* DEL ARQGRUP.DB*
if exist ARQ*.NTX DEL ARQ*.NTX
if exist DB*.ARQ DEL DB*.ARQ
if exist FCGRUPO.DB* DEL FCGRUPO.DB*
if exist FCG*.NTX DEL FCG*.NTX
if exist DB*.FCG DEL DB*.FCG
if exist REGIAO.DB* DEL REGIAO.DB*
if exist REG*.NTX DEL REG*.NTX
if exist DB*.REG DEL DB*.REG
if exist COBRADOR.DB* DEL COBRADOR.DB*
if exist COB*.NTX DEL COB*.NTX
if exist DB*.COB DEL DB*.COB
if exist PCBRAD.DB* DEL PCBRAD.DB*
if exist PCB*.NTX DEL PCB*.NTX
if exist DB*.PCB DEL DB*.PCB
if exist FCCOB.DB* DEL FCCOB.DB*
if exist FCC*.NTX DEL FCC*.NTX
if exist DB*.FCC DEL DB*.FCC
if exist CIRCULAR.DB* DEL CIRCULAR.DB*
if exist CIR*.NTX DEL CIR*.NTX
if exist DB*.CIR DEL DB*.CIR
if exist CPRCIRC.DB* DEL CPRCIRC.DB*
if exist CPR*.NTX DEL CPR*.NTX
if exist DB*.CPR DEL DB*.CPR
if exist FNCS.DB* DEL FNCS.DB*
if exist FNC*.NTX DEL FNC*.NTX
if exist DB*.FNC DEL DB*.FNC
if exist JUROS.DB* DEL JUROS.DB*
if exist JUR*.NTX DEL JUR*.NTX
if exist DB*.JUR DEL DB*.JUR
if exist HISTORIC.DB* DEL HISTORIC.DB*
if exist HIS*.NTX DEL HIS*.NTX
if exist DB*.HIS DEL DB*.HIS
if exist CGRUPOS.DB* DEL CGRUPOS.DB*
if exist CGR*.NTX DEL CGR*.NTX
if exist DB*.CGR DEL DB*.CGR
if exist COECOB.DB* DEL COECOB.DB*
if exist COE*.NTX DEL COE*.NTX
if exist DB*.COE DEL DB*.COE
if exist CINSCRIT.DB* DEL CINSCRIT.DB*
if exist CIN*.NTX DEL CIN*.NTX
if exist DB*.CIN DEL DB*.CIN
if exist CTAXAS.DB* DEL CTAXAS.DB*
if exist CTA*.NTX DEL CTA*.NTX
if exist DB*.CTA DEL DB*.CTA
if exist PRODUTOS.DB* DEL PRODUTOS.DB*
if exist PRO*.NTX DEL PRO*.NTX
if exist DB*.PRO DEL DB*.PRO
if exist TFILIAIS.DB* DEL TFILIAIS.DB*
if exist TFI*.NTX DEL TFI*.NTX
if exist DB*.TFI DEL DB*.TFI
if exist TXENTR.DB* DEL TXENTR.DB*
if exist TXE*.NTX DEL TXE*.NTX
if exist DB*.TXE DEL DB*.TXE
if exist BXREC.DB* DEL BXREC.DB*
if exist BXR*.NTX DEL BXR*.NTX
if exist DB*.BXR DEL DB*.BXR
if exist ALENDER.DB* DEL ALENDER.DB*
if exist ALE*.NTX DEL ALE*.NTX
if exist DB*.ALE DEL DB*.ALE
if exist BXFCC.DB* DEL BXFCC.DB*
if exist BXF*.NTX DEL BXF*.NTX
if exist DB*.BXF DEL DB*.BXF
if exist BXTXAS.DB* DEL BXTXAS.DB*
if exist BXT*.NTX DEL BXT*.NTX
if exist DB*.BXT DEL DB*.BXT
if exist TROTXAS.DB* DEL TROTXAS.DB*
if exist TRO*.NTX DEL TRO*.NTX
if exist DB*.TRO DEL DB*.TRO
if exist MENSAG.DB* DEL MENSAG.DB*
if exist MEN*.NTX DEL MEN*.NTX
if exist DB*.MEN DEL DB*.MEN
if exist PAR_ADM.DB* DEL PAR_ADM.DB*
if exist ADP_*.SYS DEL ADP_*.SYS
if exist ADPPW.SYS DEL ADP*.SYS
if exist ADPPW.NTX DEL ADP*.NTX
